import cabecera from "../interfaces/cabecera";
import sessionWithIdDeCabecera from "../interfaces/sessionWithIdDeCabecera";

export const defaultCabeceras:Array<cabecera> = 
[
  {
    id:"si" ,
    title: "SESIONES CABECERA1",
  },
  {
    id: "no",
    title: "SESIONES CABECERA 2",
  },
  {
    id: "2",
    title: "SESIONES CABECERA3",
  },
  {
    id: "3",
    title: "SESIONES CABECERA 4",
  },
  {
    id: "4",
    title: "SESIONES CABECERA 5",
  },
  {
    id: "5",
    title: "SESIONES CABECERA 6",
  },
];

export const defaultSessions:Array<sessionWithIdDeCabecera> =  
[
  {
    title: "SESION4",
    id:'1',
    idCabecera:"si",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION5",
    id:'22',
    idCabecera:"si",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION6",
    id:'33',
    idCabecera:"si",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION7",
    id:'44',
    idCabecera:"no",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION8",
    id:'55',
    idCabecera:"no",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'6',
    idCabecera:"no",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'7',
    idCabecera:"no",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'8',
    idCabecera:"2",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'9',
    idCabecera:"no",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'10',
    idCabecera:"2",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'11',
    idCabecera:"si",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'12',
    idCabecera:"3",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'13',
    idCabecera:"3",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'14',
    idCabecera:"3",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'15',
    idCabecera:"2",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'16',
    idCabecera:"4",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'17',
    idCabecera:"3",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'18',
    idCabecera:"4",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'19',
    idCabecera:"4",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'20',
    idCabecera:"2",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'21',
    idCabecera:"5",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'25',
    idCabecera:"5",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
  {
    title: "SESION9",
    id:'23',
    idCabecera:"5",
    content: "",
    date: "",
    horaInicio: "",
    horaTermino: "",
    tipoDeTransmision: "",
  },
]

